baseURL = "https://blair55.github.io"
title = "Tech Nick"
theme = "hugo-notepadium"

# Copyright notice. Note: You can use HTML tag here
# copyright = "&copy; 2021 Nicholas Blair"
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
pagination.pagerSize = 100

# Edit this if you want to translate your blog
defaultContentLanguage = "en"

# Code Highlighting (Chroma)
# pygmentsCodeFences = true
# pygmentsUseClasses = true

[markup]
  [markup.highlight]
    style = 'nord'

[taxonomies]
	tag = "tags"

[params]
	# If false, use minified CSS (ui.min.css)
	debugCSS = false
	# Custom CSS
	customCSS = []
	
	# List of sections support disqus comments
	disqusSections = []
	# Site meta description
	description = "Nick talks tech"
	# Site's Tagline (Subtitle or Keyword)
	tagline = "Nick talks tech"
	# If true give attribution to this theme
	themeAttrib = false
	# URL to license file, can be outside of your domain
	# licenseURL = "/about/license"

	# Configure which section for Latest Posts
	mainSections = ["blog", "post"]
	# postSections = ["blog", "post"]
	postSection = "blog"
	# Configure which section for Latest Works
	# workSection = "work"

	# 404 Configuration
	head404 = "Sorry, I can't find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	# Color of your website's accent
	colorTheme = "#ff8181"
	# Maximum number of item in Latest Posts or Works
	latestCount = 10
	# Path to site's favicon image
	faviconImg = ""
	# Date format in item list
	dateFmt = "Jan 02, 2006"



[[params.nav.custom]]
	title = "About"
	url = "https://nickblair.dev/"
[params.profile]
  enable = true
  avatar = "/img/avatar.jpg"
#   name = "XXX"
#   bio = "XXX"  # support markdown syntax
  github = "blair55"  # https://github.com/blair55
  bluesky = "nickblair.dev"  # https://bsky.app/profile/nickblair.dev

# [params.rtwt]
#   sidePane = true
#   countPageItems = 70

# [params.rtwt.home]
#   showBio = false
#   showAuthorImg = true
#   sidePaneTags = true
#   showFeatured = true
#   showRecent = true
#   hideRecentWhenFeatured = true
#   countRecent = 50

# [params.rtwt.side.home]
#   sidePaneSticky = false
#   taxonomies = ['tags']
#   countTaxonomy = 50

# [params.rtwt.side.single]
#   sidePaneSticky = true
#   showDetails = false
#   showTableOfContents = true
#   showAttachments = true
#   showRelated = false
#   countRelated = 50